-- Detect Azure brute force attempts that succeeded or failed due to MFA.
SELECT EVENT_TIME,
       CALLER_IP_ADDRESS,
       CATEGORY,
       IDENTITY,
       LOCATION,
       OPERATION_NAME,
       PROPERTIES_APP_ID,
       PROPERTIES_CLIENT_APP_USED,
       PROPERTIES_CONDITIONAL_ACCESS_STATUS,
       PROPERTIES_IS_INTERACTIVE,
       PROPERTIES_TOKEN_ISSUER_TYPE,
       RESULT_DESCRIPTION,
       RESULT_TYPE,
       PROPERTIES_APP_DISPLAY_NAME,
       PROPERTIES_USER_PRINCIPAL_NAME,
       PROPERTIES:userAgent             AS USER_AGENT
FROM RAW.AZURE_SIGNIN
WHERE USER_AGENT ILIKE '%fasthttp%'
AND EVENT_TIME BETWEEN '2024-12-15 00:00:01' and '2025-01-17 23:59:01'
AND RESULT_TYPE IN (0,50076) -- successful login or login that failed due to MFA
