---- Query B - File Events related to AnyDesk
SELECT EVENT_TIME,
       AGENT_ID,
       AGENT_EXTERNAL_IP,
       DEVICE_PLATFORM,
       INITIATING_PROCESS_NAME,
       INITIATING_PROCESS_PATH,
       INITIATING_PROCESS_COMMANDLINE,
       INITIATING_PROCESS_HASH_SHA256,
       TARGET_FILE_NAME,
       TARGET_FILE_PATH,
       TARGET_FILE_HASH_SHA256,
       TARGET_FILE_ACTION,
       IS_REMOTE_SHARE
FROM INVESTIGATION.EDR_FILE_EVENTS
WHERE (TARGET_FILE_NAME ILIKE '%ANYDESK%' OR TARGET_FILE_PATH ILIKE '%ANYDESK%' OR INITIATING_PROCESS_NAME ILIKE '%ANYDESK%')
AND EVENT_TIME BETWEEN '2023-12-15 00:00:01' and '2024-02-05 00:00:59'
